plugins {
    id 'eclipse'
    id 'idea'
    id 'maven-publish'
    id 'net.minecraftforge.gradle' version '[6.0,6.2)'
}

group = 'com.zixu.herobrine'
version = '1.0.0'
archivesBaseName = 'HeroBrineJoinTheGame'

java.toolchain.languageVersion = JavaLanguageVersion.of(17)

minecraft {
    mappings channel: 'official', version: '1.20.1'
    copyIdeResources = true

    runs {
        configureEach {
            workingDirectory project.file('run')
            property 'forge.logging.markers', 'REGISTRIES'
            property 'forge.logging.console.level', 'debug'
            mods {
                herobrine {
                    source sourceSets.main
                }
            }
        }
        client {}
        server {}
    }
}

repositories {}

dependencies {
    minecraft 'net.minecraftforge:forge:1.20.1-47.2.0'
}

tasks.named('jar', Jar).configure {
    manifest {
        attributes([
            'Specification-Title': 'Hero Brine Join The Game',
            'Specification-Vendor': 'ZI_XU',
            'Specification-Version': '1',
            'Implementation-Title': project.name,
            'Implementation-Version': project.version
        ])
    }
}
